bootchating/bootchating/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import django_rq

urlpatterns = [

    url(r'^', include('webboard.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/',include('authentication.urls')),
    url(r'^django-rq/', include('django_rq.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bootchating/webboard/urls.py
from .views import IndexView,BoardView,NewBoardView,TopicPosts,ReplyTopic,ElasticSearchApi
from django.conf.urls import url


urlpatterns=[
    url(r"^$", IndexView.as_view(),name="home"),
    url(r'^boards/(?P<pk>\d+)/$', BoardView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', NewBoardView.as_view(), name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', TopicPosts.as_view(), name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', ReplyTopic.as_view(), name='reply_topic'),
    url(r'^elastic_search/$', ElasticSearchApi.as_view(), name='elastic_search'),


]

bootchating/webboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils.html import mark_safe
from .search import PropertyIndex
# from markdown import markdown

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
    	return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics' , on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics',on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
    	return self.subject

    def indexing(self):

        """

        Add index on elastic search doc

        """
        
        obj = PropertyIndex(

            meta={'id': self.id},

            subject=self.subject,
        )

        obj.save(index="property_index")

        return obj.to_dict(include_meta=True)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+',on_delete=models.CASCADE)

    # def get_message_as_markdown(self):
    #     return mark_safe(markdown(self.message, safe_mode='escape'))

bootchating/webboard/forms.py
from django import forms
from .models import Topic,Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ), max_length=4000,help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

bootchating/webboard/views.py
from django.shortcuts import render
from rest_framework.views import APIView	
from rest_framework.permissions import IsAuthenticated,AllowAny
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404,redirect
from .models import *
from .forms import NewTopicForm,PostForm
# Create your views here.
from django.db.models import Count


class IndexView(APIView):
	permission_classes = (AllowAny,)

	def get(self,request):
		boards = Board.objects.all()
		return render(request, 'home.html', {'boards': boards})

class BoardView(APIView):
    permission_classes = (AllowAny,)

    def get(self,request,pk):
        board = Board.objects.get(pk=pk)
        topic = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return render(request, 'topics.html', {'board': board,'topic':topic})


class NewBoardView(APIView):
	permission_classes = (AllowAny,)

	def get(self,request,pk):
		board = get_object_or_404(Board, pk=pk)
		return render(request, 'new_topic.html', {'board': board})

	def post(self,request,pk):
		board = get_object_or_404(Board, pk=pk)
		subject = request.POST['subject']
		message = request.POST['message']

		user = User.objects.get(username='rakesh')  # TODO: get the currently logged in user

		topic = Topic.objects.create(
			subject=subject,
			board=board,
			starter=user
		)

		post = Post.objects.create(
			message=message,
			topic=topic,
			created_by=user
		)
		return redirect('board_topics', pk=board.pk)

class TopicPosts(APIView):
    permission_classes = (AllowAny,)
    def get(self,request,pk,topic_pk):
        topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
        topic.views +=1
        topic.save()
        return render(request, 'topic_posts.html', {'topic': topic})

class ReplyTopic(APIView):
	permission_classes = (AllowAny,)

	def get(self,request,pk,topic_pk):
		topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
		form = PostForm()
		return render(request, 'reply_topic.html', {'topic': topic, 'form': form})

	def post(self,request,pk, topic_pk):
		form = PostForm(request.POST)
		topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
		if form.is_valid():
			post = form.save(commit=False)
			post.topic = topic
			post.created_by = topic.starter
			post.save()
			return redirect('topic_posts', pk=pk, topic_pk=topic_pk)


class ElasticSearchApi(APIView):
	def post(self, request):

		try:
			search_value = (request.data).get('search_value')

			search_value_format = '"{}"'.format(search_value)

			# Filter data from ElasticSeach dataset

			es = Elasticsearch()

			search = Search(using=es)

			s = search.update_from_dict(

				{"query": {"multi_match": {"fields": [

					"city", "state", "address", "zipcode"], "query": search_value_format, "type": "phrase_prefix"}}}

			)

			total = s.count()

			s = s[0:25]

			response = s.execute()

			data = response.hits.hits

			data = {"data": data}

			return Response(data, status=status.HTTP_200_OK)

			except Exception as error:

			return Response(status=status.HTTP_404_NOT_FOUND)

bootchating/webboard/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">


  </head>
  <body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      <div class="dropdown float-right">
        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true">rakesh</a>
      <ul class="dropdown-menu">
        <li><a href="#">My account</a></li>
        <li><a href="#">Change password</a></li>
        <li><a href="#">Log out</a></li>
      </ul>
    </div>
    </div>
  </div>
</nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

{% block javascript %}{% endblock %}
  </body>
</html>

bootchating/webboard/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bootchating/webboard/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">{{ board.get_posts_count }}</td>
          <td class="align-middle">{{ board.topics.count }}</td>
          <td class="align-middle">
            {% with post=board.get_last_post %}
              <small>
                <a href="#">
                  By {{ post.created_by.username }} at {{ post.created_at }}
                </a>
              </small>
            {% endwith %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

bootchating/webboard/templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

bootchating/webboard/templates/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post a reply{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block javascript %}
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post Reply</button>
  </form>

  {% for post in topic.posts.all %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at }}</small>
          </div>
        </div>
        {{ post.get_message_as_markdown }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

bootchating/webboard/templates/topic_posts.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in topic.posts.all %}
    <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
{% if forloop.first %}
      <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
    {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'img/avatar.svg' %}" alt="{{ post.created_by.username }}" class="w-100">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.get_message_as_markdown }}   {{ post.created_by.username }}
            {% if post.created_by.username == "admin" %}
              <div class="mt-3">
                <a href="#" class="btn btn-primary btn-sm" role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock %}

bootchating/webboard/templates/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topic %}
        <tr>
          <td><a href="{% url 'topic_posts' board.pk topic.pk %}">{{ topic.subject }}</a></td>
          <td>{{ topic.starter.username }}</td>
          <td>{{ topic.replies }}</td>
          <td>{{ topic.views }}</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}